//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwitchAPIHandler {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PathStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PathStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TwitchAPIHandler.PathStrings", typeof(PathStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitch.tv/kraken/users/{0}/follows/channels/{1}?oauth_token={2}.
        /// </summary>
        internal static string FOLLOW_USER {
            get {
                return ResourceManager.GetString("FOLLOW_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitch.tv/kraken/streams/featured?limit=8&amp;offset=0&amp;hls=true.
        /// </summary>
        internal static string FRONT_PAGE_STREAMS_PATH {
            get {
                return ResourceManager.GetString("FRONT_PAGE_STREAMS_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitch.tv/kraken/users/{0}/follows/channels?&amp;offset={1}&amp;limit=16&amp;sortby=last_broadcast.
        /// </summary>
        internal static string GET_ALL_FOLLOWED_STREAMS {
            get {
                return ResourceManager.GetString("GET_ALL_FOLLOWED_STREAMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitch.tv/kraken/oauth2/authorize?response_type=token&amp;client_id=b4v9ttxqtldlobe5jswfqdhrmzp52hi&amp;redirect_uri=http://localhost&amp;scope=user_read chat_login user_follows_edit.
        /// </summary>
        internal static string GET_AUTHORIZATION_TOKEN {
            get {
                return ResourceManager.GetString("GET_AUTHORIZATION_TOKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitch.tv/kraken/streams/followed?oauth_token={0}&amp;offset={1}&amp;limit=8.
        /// </summary>
        internal static string GET_FOLLOWED_STREAMS {
            get {
                return ResourceManager.GetString("GET_FOLLOWED_STREAMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitch.tv/kraken/streams/{0}.
        /// </summary>
        internal static string GET_STREAM {
            get {
                return ResourceManager.GetString("GET_STREAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitch.tv/kraken/user?oauth_token={0}.
        /// </summary>
        internal static string GET_USER_PATH {
            get {
                return ResourceManager.GetString("GET_USER_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitch.tv/kraken/users/{0}/follows/channels/{1}.
        /// </summary>
        internal static string IS_STREAM_FOLLOWED_PATH {
            get {
                return ResourceManager.GetString("IS_STREAM_FOLLOWED_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://usher.twitch.tv/api/channel/hls/{0}.m3u8?token={1}&amp;sig={2}.
        /// </summary>
        internal static string M3U8_PATH {
            get {
                return ResourceManager.GetString("M3U8_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Assets/noBoxArt.jpg.
        /// </summary>
        internal static string NO_BOX_ART {
            get {
                return ResourceManager.GetString("NO_BOX_ART", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitch.tv/kraken/search/games?&amp;offset={1}&amp;q={0}&amp;live=true&amp;hls=true&amp;type=suggest.
        /// </summary>
        internal static string SEARCH_GAME_PATH {
            get {
                return ResourceManager.GetString("SEARCH_GAME_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitch.tv/kraken/search/streams?limit=8&amp;offset={1}&amp;q={0}&amp;live=true.
        /// </summary>
        internal static string SEARCH_STREAM_PATH {
            get {
                return ResourceManager.GetString("SEARCH_STREAM_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://api.twitch.tv/api/channels/{0}/access_token.
        /// </summary>
        internal static string TOKEN_PATH {
            get {
                return ResourceManager.GetString("TOKEN_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitch.tv/kraken/games/top?limit=8&amp;offset={0}&amp;hls=true.
        /// </summary>
        internal static string TOP_GAMES_PATH {
            get {
                return ResourceManager.GetString("TOP_GAMES_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitch.tv/kraken/streams?game={0}&amp;hls=true&amp;limit=8&amp;offset={1}.
        /// </summary>
        internal static string TOP_STREAMS_FOR_GAME_PATH {
            get {
                return ResourceManager.GetString("TOP_STREAMS_FOR_GAME_PATH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.twitch.tv/kraken/streams?hls=true&amp;limit=8&amp;offset={0}.
        /// </summary>
        internal static string TOP_STREAMS_PATH {
            get {
                return ResourceManager.GetString("TOP_STREAMS_PATH", resourceCulture);
            }
        }
    }
}
